# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-30 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
